# -- deinの書き方 --
# hook_add: プラグインが dein.vim によって追加されたとき
# hook_source: プラグインが読み込まれる直前
# hook_post_source: プラグインが読み込まれた直後
# hook_post_update: プラグインが更新された直後
#
#
#
# ------------------
# [[plugins]]
# repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vimproc.vim.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'rytkmt/dotfiles'

[[plugins]]
repo = 'rytkmt/lighthouse'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/unite.vim.rc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/lightline.vim.rc.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/indentLine.rc.vim
'''

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
"submodeを抜け出すときのコマンドを有効に
let g:submode_keep_leaving_key=1
let g:submode_timeout=0
autocmd MyAutoCmd VimEnter * source $XDG_CONFIG_HOME/plugins/vim-submode.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimshell'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vimshell.rc.vim
'''

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/emmet-vim.rc.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-rails'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-rails.rc.vim
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
depends = ['vim-textobj-ruby']
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-expand-region.rc.vim
'''

# [[plugins]]
# repo = 'stevemadere/ruby-matchit'

[[plugins]]
repo = 'vimtaku/hl_matchit.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/hl_matchit.vim.rc.vim
'''

[[plugins]]
repo = "kana/vim-textobj-user"

[[plugins]]
repo = "h1mesuke/textobj-wiw"
hook_add = '''
source $XDG_CONFIG_HOME/plugins/textobj-wiw.rc.vim
'''

[[plugins]]
repo = "kana/vim-textobj-function"

[[plugins]]
repo = "kana/vim-textobj-line"

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
hook_add = '''
let g:textobj_ruby_more_mappings = 1
'''

[[plugins]]
repo = 'vim-scripts/grep.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/grep.vim.rc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/tcomment_vim.rc.vim
'''

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-trailing-whitespace.rc.vim
'''

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-rooter.rc.vim
'''

[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/switch.vim.rc.vim
'''

[[plugins]]
repo = 'tyru/capture.vim'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-surround.rc.vim
'''

[[plugins]]
repo = "kana/vim-smartinput"
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-smartinput-endwise.rc.vim
'''

[[plugins]]
repo = "cohama/vim-smartinput-endwise"

[[plugins]]
repo = "alvan/vim-closetag"
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-closetag.rc.vim
'''

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-ref.rc.vim
'''

[[plugins]]
repo = 'tyru/vim-altercmd'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-altercmd.rc.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'maralla/vim-toml-enhance'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-toml-enhance.rc.vim
'''

#[[plugins]]
#repo = 'gko/vim-coloresque'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/ctrlp.vim.rc.vim
'''

[[plugins]]
repo = 'lilydjwg/colorizer'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/colorizer.rc.vim
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'


[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/previm.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'
hook_post_source = '''
source $XDG_CONFIG_HOME/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-quickrun.rc.vim
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-markdown.rc.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_do_mapping = 0
source $XDG_CONFIG_HOME/plugins/vim-easymotion.rc.vim
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/incsearch.vim.rc.vim
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'rytkmt/vim-textile'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/yankround.vim.rc.vim
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-easy-align.rc.vim
'''

[[plugins]]
repo = 'rytkmt/scratch.vim'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/scratch.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'thinca/vim-visualstar'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-visualstar.rc.vim
'''
